// Environment pipeline: one prompt in ("build a Santa Monica home" + links, "build a street" + a place), a manifest out.
//   research  links resolved (lib/refs.js) and places mapped (lib/map.js) into envs/<id>/
//   compose   a Claude Code session follows the environment skill: scenario doc, plan, scene models, validation, stills
//   verify    every produced model is validated and rendered again by this process
//   finish    gallery rebuilt, envs/<id>/manifest.json written
// Used by bin/env.js and the MCP tools build_environment / environment_status.
'use strict';
const fs = require('fs');
const path = require('path');
const { HERE, PROPS, PARENT, ENVS, DIST, propsLib } = require('./paths.js');
const { Progress, oneLine, readStatus } = propsLib('progress.js');
const { resolveLinks } = propsLib('refs.js');
const { slugify } = propsLib('prompt.js');
const gen = propsLib('generate.js');
const { fetchMap, addElevation } = require('./map.js');
const { envSystemPrompt, envAgentPrompt } = require('./prompt.js');
const root = PARENT;   // paths reported to callers are relative to the parent folder

const TYPES = [['street', /\b(street|block|road|avenue|boulevard|corner|intersection|neighbou?rhood|city|town|district)\b/i],
  ['park', /\b(park|playground|garden|square|plaza)\b/i], ['home', /\b(home|house|apartment|flat|interior|inside|rooms?)\b/i]];
function detectType(prompt) { for (const [t, re] of TYPES) if (re.test(prompt)) return t; return 'home'; }
function detectPlace(prompt) {
  const clean = prompt.replace(/https?:\/\/\S+/g, '').trim();
  const m = clean.match(/\b(?:at|near|around)\s+(.+?)(?:\s+(?:with|using|then|and then|plus)\b|[):]|$)/i);
  if (!m) return null;
  const cand = m[1].replace(/[.\s]+$/, '').trim();
  // only accept things that look like an address or an intersection
  return cand.length < 90 && /(^\d+\s+\S|\s&\s|\s(?:and|at)\s[A-Z]|,\s*[A-Z])/.test(cand) ? cand : null;
}
const ENV_TOOLS = ['Read', 'Write', 'Edit', 'WebFetch', 'WebSearch', 'Bash(node props/tools/validate.js:*)', 'Bash(node props/tools/still.js:*)', 'Bash(node props/tools/fetch-ref.js:*)',
  'Bash(node props/tools/build-gallery.js:*)', 'Bash(node props/bin/prop.js:*)', 'Bash(node environments/bin/env.js map:*)'];

async function buildEnvironment(opts) {
  const prompt = (opts.prompt || '').trim(); if (!prompt) throw new Error('prompt is required');
  const type = opts.type || detectType(prompt);
  const slug = slugify(opts.id || prompt.replace(/https?:\/\/\S+/g, '').replace(/\b(build|make|create|generate|a|an|the|please)\b/gi, ' ').trim());
  const dir = path.join(ENVS, slug); fs.mkdirSync(dir, { recursive: true }); fs.mkdirSync(DIST, { recursive: true });
  const model = gen.pickModel(opts.model || process.env.PROP_MODEL, 'scene');
  const prog = new Progress({ id: slug, backend: 'env', kind: 'scene', quiet: opts.quiet, onEvent: opts.onProgress, dir: DIST });
  const request = { id: slug, prompt, type, links: opts.links || [], place: opts.place || detectPlace(prompt), lat: opts.lat, lon: opts.lon, radius: opts.radius || 120, model, when: new Date().toISOString() };
  fs.writeFileSync(path.join(dir, 'request.json'), JSON.stringify(request, null, 2));
  let manifest = { id: slug, type, prompt, ok: false };
  try {
    prog.stage('start', type + ' environment "' + slug + '" on ' + model);
    // ---- research
    prog.stage('research');
    const linkTexts = [prompt].concat(request.links);
    let notes = [], images = [], unresolved = [];
    if (linkTexts.join(' ').match(/https?:\/\//)) { const r = await resolveLinks(linkTexts, slug, (m) => prog.log(m)); notes = r.notes; images = r.images; unresolved = r.unresolved; }  // images land in props/refs
    let mapFile = null, map = null;
    if (request.place || (request.lat != null && request.lon != null)) {
      try {
        map = await fetchMap({ place: request.place, lat: request.lat, lon: request.lon, radius: request.radius }); prog.log('map: ' + map.summary);
        try { await addElevation(map); prog.log('elevation: ' + map.ground.samples + ' samples, ground slope ' + (Math.hypot(map.ground.a, map.ground.b) * 100).toFixed(1) + '%'); } catch (e) { prog.log('elevation unavailable: ' + e.message); }
        mapFile = path.join(dir, 'map.json'); fs.writeFileSync(mapFile, JSON.stringify(map, null, 1));
        // also as a data module a model can load in Node and in the browser gallery: props/models/_data/<id>-map.js
        const dataDir = path.join(PROPS, 'models', '_data'); fs.mkdirSync(dataDir, { recursive: true });
        fs.writeFileSync(path.join(dataDir, slug + '-map.js'), '// map data for the ' + slug + ' environment, generated by environments/lib/map.js\n(function (d) { if (typeof module !== \'undefined\' && module.exports) module.exports = d; else (window.PROP_DATA = window.PROP_DATA || {})[\'' + slug + '-map\'] = d; })(' + JSON.stringify(map) + ');\n');
        request.mapModule = 'props/models/_data/' + slug + '-map.js';
      }
      catch (e) { prog.log('map lookup failed: ' + e.message); notes.push('Map lookup failed for "' + request.place + '": ' + e.message); }
    } else if (type !== 'home') prog.log('no place given; the session will lay out a generic ' + type);
    fs.writeFileSync(path.join(dir, 'research.json'), JSON.stringify({ notes, images: images.map((p) => path.relative(root, p)), unresolved, map: mapFile ? path.relative(root, mapFile) : null }, null, 2));
    // ---- compose
    prog.stage('compose', 'session on ' + model);
    const agent = envAgentPrompt({ slug, type, prompt, notes, unresolved, images, mapFile, map, place: request.place });
    const r = await gen.askClaudeCode({ system: envSystemPrompt(), prompt: agent, model, allowedTools: ENV_TOOLS, maxTurns: opts.maxTurns || 80, cwd: PARENT, onEvent: envTracker(prog) });
    manifest.session = { model: r.model || model, turns: r.turns, summary: oneLine(r.text, 800) };
    // ---- verify: what did the session produce?
    prog.stage('verify');
    let produced = null;
    try { produced = JSON.parse(fs.readFileSync(path.join(dir, 'manifest.json'), 'utf8')); } catch (e) { produced = null; }
    let ids = (produced && produced.models) || [];
    if (!ids.length) ids = fs.readdirSync(path.join(PROPS, 'models')).filter((f) => f.startsWith(slug) && f.endsWith('.js')).map((f) => f.replace(/\.js$/, ''));
    if (!ids.length) throw new Error('the session produced no models for ' + slug + '. It said: ' + oneLine(r.text, 400));
    manifest.models = [];
    for (const id of ids) {
      const rep = gen.runValidate(id, { export: true });
      const entry = { id, ok: !!rep.ok, tris: rep.tris, kind: rep.kind, errors: rep.errors || [], warnings: rep.warnings || [], exports: rep.exports || [] };
      if (rep.ok) { try { entry.still = path.relative(root, require(path.join(PROPS, 'tools', 'still.js')).still(id)); } catch (e) { entry.stillError = String(e.message || e); } }
      entry.exports = entry.exports.map((x) => path.join('props', x));
      prog.log((rep.ok ? 'PASS ' : 'FAIL ') + id + (rep.tris ? ' ' + rep.tris + ' tris' : '') + (rep.errors && rep.errors.length ? ': ' + rep.errors[0] : ''));
      manifest.models.push(entry);
    }
    manifest.ok = manifest.models.every((m) => m.ok);
    manifest.docs = (produced && produced.docs) || fs.readdirSync(dir).filter((f) => f.endsWith('.md')).map((f) => path.relative(root, path.join(dir, f)));
    manifest.subject = produced && produced.subject || null;
    manifest.notes = produced && produced.notes || null;
    // ---- finish
    prog.stage('finish');
    try { require(path.join(PROPS, 'tools', 'build-gallery.js')); manifest.gallery = 'props/dist/gallery.html'; } catch (e) { manifest.galleryError = String(e); }
    prog.finish(manifest.ok);
    manifest.elapsed = prog.snapshot().elapsed; manifest.research = { notes, images: images.map((p) => path.relative(root, p)), map: mapFile ? path.relative(root, mapFile) : null };
    manifest.request = request; manifest.log = path.relative(root, prog.logFile);
    fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
    fs.writeFileSync(path.join(DIST, slug + '.result.json'), JSON.stringify(manifest, null, 2));
    return manifest;
  } catch (e) {
    prog.finish(false);
    manifest.error = String(e && e.message || e); manifest.elapsed = prog.snapshot().elapsed;
    fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2));
    fs.writeFileSync(path.join(DIST, slug + '.result.json'), JSON.stringify(manifest, null, 2));
    throw e;
  }
}

// Session events onto the compose stage: just log what it is doing.
function envTracker(prog) {
  const rel = (f) => path.relative(root, path.resolve(f || ''));
  return (ev) => {
    if (ev.type === 'system' && ev.subtype === 'init') { prog.log('session started' + (ev.model ? ' on ' + ev.model : '')); return; }
    if (ev.type === 'assistant' && ev.message && Array.isArray(ev.message.content)) {
      for (const b of ev.message.content) {
        if (b.type === 'text' && b.text && b.text.trim()) { prog.log('says: ' + oneLine(b.text, 110)); continue; }
        if (b.type !== 'tool_use') continue;
        const inp = b.input || {}, f = inp.file_path || '', cmd = inp.command || '';
        if (b.name === 'Read') prog.log('reading ' + rel(f));
        else if (b.name === 'Write') prog.log('writing ' + rel(f));
        else if (b.name === 'Edit') prog.log('editing ' + rel(f));
        else if (b.name === 'Bash') prog.log('running: ' + oneLine(cmd, 100));
        else if (b.name === 'WebFetch') prog.log('fetching ' + oneLine(inp.url || '', 80));
        else if (b.name === 'WebSearch') prog.log('searching: ' + oneLine(inp.query || '', 80));
        else prog.log('tool ' + b.name);
      }
    }
    if (ev.type === 'user' && ev.message && Array.isArray(ev.message.content)) {
      for (const b of ev.message.content) {
        if (b.type !== 'tool_result') continue;
        const text = typeof b.content === 'string' ? b.content : (Array.isArray(b.content) ? b.content.map((c) => c.text || '').join('\n') : '');
        const m = text.match(/^(PASS|FAIL) .*$/gm); if (m) m.slice(0, 3).forEach((l) => prog.log('validator: ' + oneLine(l, 100)));
        if (b.is_error) prog.log('tool error: ' + oneLine(text, 110));
      }
    }
    if (ev.type === 'result') prog.log('session finished after ' + (ev.num_turns || '?') + ' turns');
  };
}

function listEnvironments() {
  const dir = ENVS; if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir).filter((d) => !d.startsWith('_') && (fs.existsSync(path.join(dir, d, 'request.json')) || fs.existsSync(path.join(dir, d, 'manifest.json')))).map((d) => {
    let m = null; try { m = JSON.parse(fs.readFileSync(path.join(dir, d, 'manifest.json'), 'utf8')); } catch (e) { /* not finished */ }
    return { id: d, ok: m ? m.ok : null, type: m ? m.type : null, models: m && m.models ? m.models.map((x) => typeof x === 'string' ? x : x.id) : [], elapsed: m ? m.elapsed : null };
  });
}

module.exports = { buildEnvironment, listEnvironments, detectType, detectPlace, ENV_TOOLS, status: (id) => readStatus(slugify(id), DIST) };
